### ISSUE TITLE
Issue with retrieving available options for a multi-select customfield

### ISSUE THREAD

**Issue by PravinrajV** [samsmu/JIRA2PM#15]
Issue with retrieving available options for a multi-select customfield.

The custom field is a multi select field. When I select this field for retrieval, "[object Object]" is what getting written to the spreadsheet.

Any thoughts!! 

![image](https://user-images.githubusercontent.com/31581909/30017759-66680034-9128-11e7-8f9e-e9601460b901.png)

**Comment by BlackCatter** [comment]
Hi!
It looks like there is a bug with presenting multi select field, will fix it this week 🔨

**Comment by PravinrajV** [comment]
Awesome.
Thank you very Much.
Will wait for the fix.


Regards,
Pravinraj Vincent

**Comment by BlackCatter** [comment]
Fixed in PR https://github.com/samsmu/JIRA2PM/pull/17

Changes were published and should be available by now 😼

Please confirm that everything working for you with custom multi-select fields

**Comment by PravinrajV** [comment]
Sure.
Let me test and confirm.


Regards,
Pravinraj Vincent

**Comment by PravinrajV** [comment]
Hi.
Multi select fields are now working fine.. Tested selecting a single value in multi select and also multiple values. They are good now.
Great work. Appreciate it.

One more: Does the "Reload custom field" do something? When i Click on it, nothing is happening. Am I missing something?

**Comment by BlackCatter** [comment]
Nice to hear that it's working!

"Reload custom field" updates the list of custom fields you have in your jira project. Custom fields are updated when you connect to JIRA automatically and this button allows to update fields manually. Nothing is happening probably because custom fields haven't changed 😺

I understand that it is very unclear, but changing UX requires a lot of time, which I sadly can't spare at the moment

**Comment by PravinrajV** [comment]
Hey no worries.

Thanks for fixing the multi select.
Thanks for your time.


Regards,
Pravinraj Vincent
